#!/usr/bin/env python3
"""
Python script to set up AI Ignore files (.cursorignore, .claudeignore, .agentsignore, .ignore)
in target paper repositories to prevent AI Agents from indexing sensitive PII research data.
Uses ONLY Python standard library.
"""

import sys
import argparse
from pathlib import Path

DEFAULT_IGNORE_PATTERNS = """# AI Agent Ignore Configuration
# Automatically generated by scholarly-agent-skills to protect sensitive research data and PII.

# Raw & Unanonymized Research Folders
raw_data/
private_data/
personal_data/
transcripts_raw/
interview_raw/
fieldnotes_private/

# Sensitive File Patterns
*.private.md
*.private.json
*.pii.csv
*.raw.txt
*.pfx
*.pem

# Credentials & Environment
.env
.env.*
credentials/
secrets/
"""

def setup_ai_ignore(target_dir: Path) -> bool:
    target_dir = target_dir.resolve()
    if not target_dir.exists():
        print(f"Error: Target directory '{target_dir}' does not exist.", file=sys.stderr)
        return False
        
    ignore_filenames = [".cursorignore", ".claudeignore", ".agentsignore", ".ignore"]
    
    print(f"🔒 Setting up AI Ignore rules in {target_dir}...")
    for filename in ignore_filenames:
        target_file = target_dir / filename
        if not target_file.exists():
            target_file.write_text(DEFAULT_IGNORE_PATTERNS, encoding="utf-8")
            print(f"  ✅ Created {filename}")
        else:
            # Check if default patterns are already included
            existing_text = target_file.read_text(encoding="utf-8")
            if "raw_data/" not in existing_text:
                updated_text = existing_text + "\n" + DEFAULT_IGNORE_PATTERNS
                target_file.write_text(updated_text, encoding="utf-8")
                print(f"  ✅ Updated {filename} with sensitive data rules")
            else:
                print(f"  ℹ️ {filename} already contains AI Ignore rules")
                
    print("🎉 AI Ignore configuration complete. Raw research data folders are protected from AI Agents.")
    return True

def main():
    parser = argparse.ArgumentParser(description="Configure AI Ignore rules in target paper repository.")
    parser.add_argument("target", nargs="?", default=".", help="Target paper repository directory (defaults to current directory)")
    args = parser.parse_args()
    
    success = setup_ai_ignore(Path(args.target))
    if not success:
        sys.exit(1)

if __name__ == '__main__':
    main()
